version: '3'
services:
  mysql-server:
    container_name: mysql-server
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: springuser
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    restart: always
  advertisement-server:
    image: advertisement-service
    depends_on:
      - "mysql-server"
    ports:
      - "8080:8080"
